function [fitresult, gof] = createFit(xx, yy, weight)
%CREATEFIT(XX,YY,WEIGHT)
%  Create a fit.
%
%  Data for 'Linear regression' fit:
%      X Input : xx
%      Y Output: yy
%      Weights : weight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jul-2018 12:36:06


%% Fit: 'Linear regression'.
[xData, yData, weights] = prepareCurveData( xx, yy, weight );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if 0
    % Plot fit with data.
    figure( 'Name', 'Linear regression' );
    h = plot( fitresult, xData, yData );
    legend( h, 'yy vs. xx with weight', 'Linear regression', 'Location', 'NorthEast' );
    % Label axes
    xlabel xx
    ylabel yy
    grid on
end

